//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string ProductName { get; set; }
        public string SerialNumber { get; set; }
        public string StockQuantity { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedON { get; set; }
    }
}
